# Data Cleaning

## Missing Data

Let's dive deeper into how to fix missing data. Before we do any cleaning, we need a fast way to spot which columns are missing data. .info() tells us which columns are complete and which ones are hiding empty values.

In [1]:
import pandas as pd

data = {
  'street': [
    '5230 Newell Road',
    '1381 9th Avenue',
    '1709 Broderick St',
    '2640 Steiner St',
    None,
    '1600 Amphitheatre Parkway',
    '7500 N Glenoaks Boulevard',
    '4501 Glencoe Avenue',
    '232 Santa Margarita Ave',
    '471 Emerson Street'
  ],
  'city': [
    'Palo Alto',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'Mountain View',
    'Burbank',
    'Marina del Rey',
    'Menlo Park',
    None
  ],
  'state': [
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    None,
    None
  ],
  'zip_code': [
    94303,
    None,
    94115,
    94123,
    94123,
    94043,
    91504,
    90292,
    94025,
    None
  ],
  'delivery_type': [
    'First Class',
    'Standard',
    'Priority',
    'Standard',
    None,
    'Expresss',
    'Standard',
    'Standard',
    None,
    None
  ]
}

addresses = pd.DataFrame(data)

### Remove Rows with **.dropna()** "Drop not avaible"

After we spot which columns are **missing data** with **.info()**, if only a small number of rows are missing data (and that data isn’t important), we can safely drop those rows with .dropna() This **removes any rows that contain at least one missing value**.

In [2]:
cleaned_adresses1 = addresses.dropna()
cleaned_adresses1

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard

We can use **subset=** if only we care about missing values in specific columns:

In [3]:
cleaned_adresses2 = addresses.dropna(subset=['street', 'zip_code'])
cleaned_adresses2

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard
8    232 Santa Margarita Ave      Menlo Park   NaN   94025.0           NaN

### Replace Missing Values with **.fillna()**

Imputation means filling in the blanks with a value that makes sense, and it wll depend on the data. For example, a default value like 'unknown', the most common value (the mode), the average value.

In [4]:
# Default value
addresses['street'] = addresses['street'].fillna('Unknown')
addresses['city'] = addresses['city'].fillna('Unknown')
addresses['state'] = addresses['state'].fillna('Unknown')

# Most common value
common_delivery_type = addresses['delivery_type'].mode()[0]
addresses['delivery_type'] = addresses['delivery_type'].fillna(common_delivery_type)

# Average value
average_zip = addresses['zip_code'].mean()
addresses['zip_code'] = addresses['zip_code'].fillna(average_zip)

# Cleaned df
addresses

                      street            city    state  zip_code delivery_type
0           5230 Newell Road       Palo Alto       CA   94303.0   First Class
1            1381 9th Avenue   San Francisco       CA   93316.0      Standard
2          1709 Broderick St   San Francisco       CA   94115.0      Priority
3            2640 Steiner St   San Francisco       CA   94123.0      Standard
4                    Unknown   San Francisco       CA   94123.0      Standard
5  1600 Amphitheatre Parkway   Mountain View       CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank       CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey       CA   90292.0      Standard
8    232 Santa Margarita Ave      Menlo Park  Unknown   94025.0      Standard
9         471 Emerson Street         Unknown  Unknown   93316.0      Standard

## Duplicate Data

Sometimes our dataset looks fine at a glance, but it secretly contains duplicate rows and if we run data analysis with duplicated data, that will lead to some strange results!

In [5]:
import pandas as pd

data = {
  'ticket_id': [
    'TKT-88421', 'TKT-88421', 'TKT-99213',
    'TKT-55310', 'TKT-55310', 'TKT-66772',
    'TKT-11890', 'TKT-11890', 'TKT-77445', 
    'TKT-33109', 'TKT-18479', 'TKT-90002'
  ],
  'passenger_name': [
    'Don Draper', 'Don Draper', 'Emily Davis',
    'Roger Sterling', 'Roger Sterling', 'Harper Stern',
    'Pete Campbell', 'Pete Campbell', 'Robert Spearing', 
    'Olivia Martinez', 'Andrew Largeman', 'Kendall Roy'
  ],
  'flight': [
    'PA102', 'PA102', 'DL404',
    'UA220', 'UA220', 'UA178',
    'AA778', 'AA778', 'BA305', 
    'DL909', 'UA347', 'PRV-JET'
  ],
  'route': [
    'LGW → LAX', 'LGA → LAX', 'ATL → SEA',
    'JFK → CDG', 'JFK → CDG', 'JFK → LHR',
    'MCI → LGA', 'MCI → LGA', 'LHR → SFO', 
    'DEN → PHX', 'LAX → EWR', 'NYC → Oslo'
  ]
}

tickets = pd.DataFrame(data)

### Find Duplicate Data with **.duplicated()**

We can use .duplicated() method to find rows that are duplicates of each other. It returns a Series of True and False values. True means that row is a duplicate:

In [6]:
tickets

    ticket_id   passenger_name   flight       route
0   TKT-88421       Don Draper    PA102   LGW → LAX
1   TKT-88421       Don Draper    PA102   LGA → LAX
2   TKT-99213      Emily Davis    DL404   ATL → SEA
3   TKT-55310   Roger Sterling    UA220   JFK → CDG
4   TKT-55310   Roger Sterling    UA220   JFK → CDG
5   TKT-66772     Harper Stern    UA178   JFK → LHR
6   TKT-11890    Pete Campbell    AA778   MCI → LGA
7   TKT-11890    Pete Campbell    AA778   MCI → LGA
8   TKT-77445  Robert Spearing    BA305   LHR → SFO
9   TKT-33109  Olivia Martinez    DL909   DEN → PHX
10  TKT-18479  Andrew Largeman    UA347   LAX → EWR
11  TKT-90002      Kendall Roy  PRV-JET  NYC → Oslo

In [7]:
print(tickets.duplicated())

# Just true values
tickets[tickets.duplicated()]

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7      True
8     False
9     False
10    False
11    False
dtype: bool

   ticket_id  passenger_name flight      route
4  TKT-55310  Roger Sterling  UA220  JFK → CDG
7  TKT-11890   Pete Campbell  AA778  MCI → LGA

### Remove Duplicates with **.drop_duplicates()**

Then, we can decide how to remove them. .drop_duplicates() remove all rows that are **exactly identical** to another row in the DataFrame.

In [8]:
no_dupes = tickets.drop_duplicates()
no_dupes

    ticket_id   passenger_name   flight       route
0   TKT-88421       Don Draper    PA102   LGW → LAX
1   TKT-88421       Don Draper    PA102   LGA → LAX
2   TKT-99213      Emily Davis    DL404   ATL → SEA
3   TKT-55310   Roger Sterling    UA220   JFK → CDG
5   TKT-66772     Harper Stern    UA178   JFK → LHR
6   TKT-11890    Pete Campbell    AA778   MCI → LGA
8   TKT-77445  Robert Spearing    BA305   LHR → SFO
9   TKT-33109  Olivia Martinez    DL909   DEN → PHX
10  TKT-18479  Andrew Largeman    UA347   LAX → EWR
11  TKT-90002      Kendall Roy  PRV-JET  NYC → Oslo

But sometimes rows aren’t exact duplicates, but you still want to remove certain **repeated values**. Luckily, most datasets have a column that *uniquely identifies each row*. For a library, this would be the book’s ISBN, or for airline tickets it will be the ticket ID.

Again, we can use **subset=** to remove duplicates based only on that column

In [9]:
unique_tickets = tickets.drop_duplicates(subset=['ticket_id'])
unique_tickets

    ticket_id   passenger_name   flight       route
0   TKT-88421       Don Draper    PA102   LGW → LAX
2   TKT-99213      Emily Davis    DL404   ATL → SEA
3   TKT-55310   Roger Sterling    UA220   JFK → CDG
5   TKT-66772     Harper Stern    UA178   JFK → LHR
6   TKT-11890    Pete Campbell    AA778   MCI → LGA
8   TKT-77445  Robert Spearing    BA305   LHR → SFO
9   TKT-33109  Olivia Martinez    DL909   DEN → PHX
10  TKT-18479  Andrew Largeman    UA347   LAX → EWR
11  TKT-90002      Kendall Roy  PRV-JET  NYC → Oslo

## Wrong Data Types

For example, a column of **numbers** might be **imported as strings**. Oftentimes, **boolean** True and False values are interpreted as strings as well. This is an issue because if you try to do math on that columns you'll get an error!

In [10]:
import pandas as pd

data = {
  'player_name': [
    'Parzival', 'Ar3mis', 'Aech', 'Kirito', 'Azuna',
    'nakedinthewoods', 'Sonny666', 'X.X', 'Fendi_Gucci', 'Professor Chaos'
  ],
  'score': [
    '1500', '2300', '1800', '2,100', '1700',
    '2000', '2200', '1600', '1900', '2k50'
  ],
  'level': [
    12, 15, 13, 14, 12, 
    13, 15, 11, 14, 13
  ],
  'time_solved': [
    '23.5', '35.2', '19.0', '14.8', '3.8',
    '42.5', '5h', '33.2', '4.3', '24.6'
  ]
}

high_scores = pd.DataFrame(data)

### Inspecting Data Types

You can use **.dtypes** to see the type of each column.

### Changing Data Types

We can use **pd.to_numeric()** to convert the data type to be a numeric.

If one of the values is something like **'twenty years old'**, Pandas won't know how to turn that into 20. In this case, pd.to_numeric will throw an error! So, we can use the parameter **errors='coerce'** to convert them to a NaN and then use one of the other strategies from earlier in this chapter to fill in that missing value

In [11]:
# We will see that score and time columns are a string
print(high_scores.dtypes)
print('\n')

# We'll change them to be numeric
high_scores['score'] = pd.to_numeric(high_scores['score'], errors='coerce')
high_scores['time_solved'] = pd.to_numeric(high_scores['time_solved'], errors='coerce')

print(high_scores.dtypes)
pd.DataFrame(high_scores)

player_name      str
score            str
level          int64
time_solved      str
dtype: object


player_name        str
score          float64
level            int64
time_solved    float64
dtype: object

       player_name   score  level  time_solved
0         Parzival  1500.0     12         23.5
1           Ar3mis  2300.0     15         35.2
2             Aech  1800.0     13         19.0
3           Kirito     NaN     14         14.8
4            Azuna  1700.0     12          3.8
5  nakedinthewoods  2000.0     13         42.5
6         Sonny666  2200.0     15          NaN
7              X.X  1600.0     11         33.2
8      Fendi_Gucci  1900.0     14          4.3
9  Professor Chaos     NaN     13         24.6

## String Manipulation

For example, if the responses in a RSVP text book were all in the same format, then we could easily use Pandas to see how many people responded "Yes". But as it currently stands, everyone answered slightly differently. we can use String manipulation to try to **standardize the responses**.

There are a handful of very helpful **.str** methods for basic string processing:

.str.lower(): makes everything lowercase
.str.upper(): makes everything uppercase
.str.strip(): removes whitespace from both ends
.str.contains('text'): checks for a substring
.str.replace('old', 'new'): replaces parts of the text

You can even chain these methods together in a single line!

In [12]:
import pandas as pd
import random

#random.seed(1)

# Different possible RSVP variants
options = ['Yes', 'yes', 'yesss', 'Yep   ', ' yes', 'YES', 'y', 'No  ', 'no', 'N ', 'n', 'no thx']

one_hundred_responses = random.choices(options, k=100)

# Generate fake names for the 100 guests
names = [f'Guest_{i+1}' for i in range(100)]

# Create the DataFrame
responses = pd.DataFrame({
  'name': names,
  'rsvp': one_hundred_responses
})

responses.head()

      name   rsvp
0  Guest_1     no
1  Guest_2      n
2  Guest_3  yesss
3  Guest_4    YES
4  Guest_5     no

There's a DataFrame named responses that has 100 RSVPs in different formats. Let's to process the text of the rsvp column and make each response either 'y' or 'n'

In [13]:
responses['rsvp'] = responses['rsvp'].str.lower().str.strip().str.replace('yes', 'y').str.replace('no', 'n')

print(responses['rsvp'].value_counts())

rsvp
y        38
n        33
yss      10
yep      10
n thx     9
Name: count, dtype: int64