# DataFrame

A DataFrame is a 2-dimensional data structure made up of rows and columns. Each column has a name and a data type (like numbers, text, or even dates).
We can sort, filter, group, modify, and analyze data easly with dataframes.

In [23]:
import pandas as pd

# Mobile apps
app_data = {
  'app_name': [
    'YouTube', 'TikTok', 'Instagram', 'Spotify', 'Duolingo', 
    'Twitter', 'Headspace', 'Discord', 'Depop'
  ],
  'category': [
    'Video', 'Social Media', 'Social Media', 'Music', 'Education',
    'Social Media', 'Health', 'Communication', 'Shopping'
  ],
  'rating': [
    4.7, 4.6, 4.5, 4.6, 4.7,
    4.3, None, 4.7, 4.4
  ],
  'downloads_millions': [
    5000, 3000, 3500, 2000, None,
    1500, 500, 600, 200
  ]
}

# Create the DataFrame
apps = pd.DataFrame(app_data)

## Data Exploration

Here are four pandas methods that can help with some basic **data exploration:**

The methods .head() and .tail() *display* the first 5 and last 5 rows (by default) of the DataFrame, respectively

In [24]:
apps.head(4)

    app_name      category  rating  downloads_millions
0    YouTube         Video     4.7              5000.0
1     TikTok  Social Media     4.6              3000.0
2  Instagram  Social Media     4.5              3500.0
3    Spotify         Music     4.6              2000.0

The .info() method will show you **information** about each column in the DataFrame and it can be used to gain a quick understanding of the *data types* stored in your DataFrame as well as how much *data is missing*.

In [25]:
apps.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   app_name            9 non-null      str
 1   category            9 non-null      str
 2   rating              8 non-null      float64
 3   downloads_millions  8 non-null      float64
dtypes: float64(2), str(2)
memory usage: 420.0 bytes

You can use .describe() to get a printout of **summary statistics** (mean, min, max, standard deviation, etc.) for every numeric column. Adding include='all' inside allows us to view stats about non-numeric columns

In [26]:
apps.describe(include="all")

       app_name      category    rating  downloads_millions
count         9             9  8.000000             8.00000
unique        9             7       NaN                 NaN
top     YouTube  Social Media       NaN                 NaN
freq          1             3       NaN                 NaN
mean        NaN           NaN  4.562500          2037.50000
std         NaN           NaN  0.150594          1687.71824
min         NaN           NaN  4.300000           200.00000
25%         NaN           NaN  4.475000           575.00000
50%         NaN           NaN  4.600000          1750.00000
75%         NaN           NaN  4.700000          3125.00000
max         NaN           NaN  4.700000          5000.00000

## Accessing Specific Columns

If we want to **access one column**, we could do it using the bracket style (it becomes a series):

In [27]:
one_column = apps["app_name"]
print(one_column)
type(one_column)

0      YouTube
1       TikTok
2    Instagram
3      Spotify
4     Duolingo
5      Twitter
6    Headspace
7      Discord
8        Depop
Name: app_name, dtype: str

pandas.Series

We can **access multiple columns** by using a Python list of column names (it is a dataframe again):

In [28]:
more_columns = apps[["app_name", "downloads_millions"]]
print(more_columns)
type(more_columns)

    app_name  downloads_millions
0    YouTube              5000.0
1     TikTok              3000.0
2  Instagram              3500.0
3    Spotify              2000.0
4   Duolingo                 NaN
5    Twitter              1500.0
6  Headspace               500.0
7    Discord               600.0
8      Depop               200.0

pandas.DataFrame

Sometimes we want **everything except one column**. That’s where .drop() comes in handy. axis=1 tells Pandas that we want to drop a column rather than a row.

In [29]:
removed_category_df = apps.drop("category", axis=1)
print(removed_category_df)

    app_name  rating  downloads_millions
0    YouTube     4.7              5000.0
1     TikTok     4.6              3000.0
2  Instagram     4.5              3500.0
3    Spotify     4.6              2000.0
4   Duolingo     4.7                 NaN
5    Twitter     4.3              1500.0
6  Headspace     NaN               500.0
7    Discord     4.7               600.0
8      Depop     4.4               200.0

## Filtering Rows

Here's how we could **filter** for apps (creating a new dataframe). For example, apps with more than 2000 millions downloads. Also can filter based on **multiple conditions** by using AND (&) and OR (|).

In [30]:
popular_apps = apps[apps["downloads_millions"] > 1000]
print(popular_apps)

popular_and_great_apps = apps[(apps["downloads_millions"] > 1000) & (apps["rating"] > 4.5)]
print(popular_and_great_apps)

    app_name      category  rating  downloads_millions
0    YouTube         Video     4.7              5000.0
1     TikTok  Social Media     4.6              3000.0
2  Instagram  Social Media     4.5              3500.0
3    Spotify         Music     4.6              2000.0
5    Twitter  Social Media     4.3              1500.0
  app_name      category  rating  downloads_millions
0  YouTube         Video     4.7              5000.0
1   TikTok  Social Media     4.6              3000.0
3  Spotify         Music     4.6              2000.0

## More Data Manipulation

We can **sort** a DataFrame by a specific column by using .sort_values(). ascending=False for high to low:

In [31]:
downloads_sorted = apps.sort_values(by="downloads_millions", ascending=False)
print(downloads_sorted)

    app_name       category  rating  downloads_millions
0    YouTube          Video     4.7              5000.0
2  Instagram   Social Media     4.5              3500.0
1     TikTok   Social Media     4.6              3000.0
3    Spotify          Music     4.6              2000.0
5    Twitter   Social Media     4.3              1500.0
7    Discord  Communication     4.7               600.0
6  Headspace         Health     NaN               500.0
8      Depop       Shopping     4.4               200.0
4   Duolingo      Education     4.7                 NaN

We can **rename** columns with .rename() method, assign the result back to apps or use inplace=True:

In [32]:
# apps = apps.rename()
apps.rename(columns={"app_name":"name", "downloads_millions":"downloads"}, inplace=True)
print(apps)

        name       category  rating  downloads
0    YouTube          Video     4.7     5000.0
1     TikTok   Social Media     4.6     3000.0
2  Instagram   Social Media     4.5     3500.0
3    Spotify          Music     4.6     2000.0
4   Duolingo      Education     4.7        NaN
5    Twitter   Social Media     4.3     1500.0
6  Headspace         Health     NaN      500.0
7    Discord  Communication     4.7      600.0
8      Depop       Shopping     4.4      200.0

We can **add new columns** by assigning a list or a calculation to a column name. Here’s how to add a "release_year" column:

In [33]:
apps["release_year"] = [2005, 2017, 2010, 2008, 2012, 2006, 2012, 2015, 2013]
print(apps.sort_values(by="release_year", ascending=False))

        name       category  rating  downloads  release_year
1     TikTok   Social Media     4.6     3000.0          2017
7    Discord  Communication     4.7      600.0          2015
8      Depop       Shopping     4.4      200.0          2013
6  Headspace         Health     NaN      500.0          2012
4   Duolingo      Education     4.7        NaN          2012
2  Instagram   Social Media     4.5     3500.0          2010
3    Spotify          Music     4.6     2000.0          2008
5    Twitter   Social Media     4.3     1500.0          2006
0    YouTube          Video     4.7     5000.0          2005